version: "3.9"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfiles/auth.Dockerfile
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app.Dockerfile
  gui:
    build:
      context: .
      dockerfile: Dockerfiles/gui.Dockerfile
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfiles/reverse-proxy.Dockerfile
    ports:
      - "80:80"