version: "3.9"
services:
  db:
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=dbPass
  auth:
    build:
      context: .
      dockerfile: Dockerfiles/auth.Dockerfile
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app.Dockerfile
    depends_on:
      - db
  gui:
    build:
      context: .
      dockerfile: Dockerfiles/gui.Dockerfile
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfiles/reverse-proxy.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth
      - app
      - gui