# Specify manifest version
apiVersion: apps/v1
# Resource is a deployment
kind: Deployment
metadata:
  # Name of the deployment (kubectl get deployments)
  name: app-url-shortener
spec:
  # Select pods to be managed by deployment
  selector:
    matchLabels:
      run: app-url-shortener
  # Create multiple pods according to the template below
  replicas: 3
  template:
    metadata:
      # Labels for selecting the pods
      labels:
        run: app-url-shortener
    spec:
      containers:
      - name: app-url-shortener
        # Specify image tag for container
        image: group6/url-shortener
        # Image is not available in the public docker registry -> use local image
        imagePullPolicy: Never
        # Set environment variables from secret
        env:
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: APP_SECRET
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: JWT_SECRET
          - name: ARANGO_URL
            value: http://app-db:8529
          - name: ARANGO_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: ARANGO_USER
          - name: ARANGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: ARANGO_PASSWORD
        # Open default flask port on the container/pod
        ports:
        - containerPort: 5000
