#! /bin/bash

set -e

# Check if docker is installed
if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: docker is not installed.' >&2
  exit 1
fi

cd "$(dirname "$0")"

for file in $(ls *.Dockerfile); do
    image_tag="group6/$(echo $file | cut -d'.' -f1)"
    echo "Building image $image_tag..."
    docker build -f $file -t $image_tag ..
done

echo -e "\nReport:"
docker images | grep ^group6/

echo -e "\nDone"
