#! /bin/bash

if ! [ -x "$(command -v docker)" ]; then
  echo 'Error: docker is not installed.' >&2
  exit 1
fi

cd "$(dirname "$0")"
dockerhub_username="luoabd"

for file in $(ls *.Dockerfile); do
    image_tag="$dockerhub_username/group6-$(echo $file | cut -d'.' -f1)"
    echo "Pushing image $image_tag..."
    docker push $image_tag
done
